# Sample configuration file for Spring Cloud Config Server
# This file demonstrates how to structure configuration files in the Git repository

# Common properties shared by all applications
app:
  common:
    property: common-value

# Database configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: dbuser
    password: dbpass

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example: DEBUG
    sun.rmi.transport.tcp: ERROR
    sun.rmi.loader: ERROR
    javax.management.remote.rmi: ERROR

# Custom application properties
my:
  service:
    url: http://example.com/api
    timeout: 30000
