# Development environment specific configuration

# Override common properties for development
app:
  common:
    property: dev-value

# Development database configuration
spring:
  datasource:
    url: jdbc:h2:mem:devdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  # Enable development features
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# Development logging configuration
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example: DEBUG
    sun.rmi.transport.tcp: ERROR
    sun.rmi.loader: ERROR
    javax.management.remote.rmi: ERROR

# Development service configuration
my:
  service:
    url: http://dev.example.com/api
    timeout: 60000
