spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///#{systemProperties['user.dir']}/../config-repo
          default-label: main

server:
  port: 8888